problem:
   name: Hardness_porosity # your problem name
algorithm:
   name: dgemo # algorithm name
experiment:
   init_sample_path: C:\Users\cepch\3d printing python\features58.csv



   n_worker: 4 # number of evaluation workers that can be run in parallel